### ISSUE TITLE
Buttons disappear after resizing window

### ISSUE THREAD

**Issue by Luckybiscuits** [pvrs12/Anesidora#30]
I resized Anesidora to a taller size so I could see more channels at once when scrolling and all the buttons are now off the window. I tried to remove and reinstall but the previous options remain. In Firefox 62.0.3, Windows 7. Image below:
![image](https://user-images.githubusercontent.com/11497150/47054174-38399500-d165-11e8-830b-d35d5a8815b9.png)

**Comment by pvrs12** [comment]
Hey, sorry I left this sit.

This is obviously not ideal... I'm working on moving the Options menu to use the standards for web extensions instead of that goofy button
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/user_interface/Options_pages

In the meanwhile (if you're still having this issue), you should be able to fix this by "Refresh"-ing firefox (although this might be more aggressive than you want)
https://support.mozilla.org/en-US/kb/refresh-firefox-reset-add-ons-and-settings

**Comment by pvrs12** [comment]
If you're still having this issue, it should be able to be fixed in the most recent version.

If you go to "Add-ons" > "Anesidora" > "Options" and scroll down you'll find the new Options menu. You should be able to update it from there, so you don't need to reach the old options button anymore.
