### ISSUE TITLE
Login transparency

### ISSUE THREAD

**Issue by miketrethewey** [pvrs12/Anesidora#38]
Hello! It seems that I may be the only one concerned, but, I did look through the source code because I was concerned about why I was immediately greeted with a "give me your username & password" dialogue. After perusing the code, I eventually saw that it's just handing it off to Pandora's site, which is what I had expected.
Other extensions (Sound Control to name one) somehow can access Pandora's data without requiring a separate log in session, likely because it does in fact require a tab to be open that has Pandora's full site sitting there.

Thoughts? I think what I would've liked was an overt explanation as to why my credentials were required.

**Comment by pvrs12** [comment]
Hey Mike, I appreciate your concern, about this. In order to avoid collecting credentials, I'd probably need to hook up some method where the user types credentials into some (still phishy looking) form. I don't have any great way to allow a user to login directly to just Pandora. 

The technical reasoning for this is that it is spoofing an Android app login, not a standard web login. It _might_ be possible to allow a user to copy their cookie from the browser, but that would require some technical skill.

As for an overt explanation, I can definitely add that. I'm thinking of just putting a little "What happens to my password?" message beneath the login. It'll provide a short explanation of why its necessary, then it'll link to all of the portions in the code where the password is used so that users can easily verify for themselves that it is not misused.

**Comment by miketrethewey** [comment]
That’s perfect! Thanks!

**Comment by pvrs12** [comment]
The newest version adds this now. It links to https://github.com/pvrs12/Anesidora/blob/master/login.md
