### ISSUE TITLE
Key Remapping

### ISSUE THREAD

**Issue by mikeyb293** [pvrs12/Anesidora#39]
Hey man, just downloaded this extension. Was wondering if there was anyway to implement usability of the 'Pause/Break' key for shortcuts. Mine happens to be right next to my media keys so a single stroke would be nicer then having to use find the alt key while gaming

**Comment by pvrs12** [comment]
Unfortunately I don't think that's possible due to limitations on what extensions can do. 

There are a few possible options for workarounds (depending on if you're using Chrome or Firefox)
1. You can switch to Ctrl if that's easier than Alt (chrome or Firefox)
2. You can bind a second media key (chrome only)
3. You can use another tool like AutoHotkey to convert a Pause/Break keypress into Alt+N (Chrome or Firefox)

Here is the documentation which explains why this isn't possible to do:
[Chrome](https://developer.chrome.com/extensions/commands)
[Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)

**Comment by mikeyb293** [comment]
> 
> 
> Unfortunately I don't think that's possible due to limitations on what extensions can do.
> 
> There are a few possible options for workarounds (depending on if you're using Chrome or Firefox)
> 
>     1. You can switch to Ctrl if that's easier than Alt (chrome or Firefox)
> 
>     2. You can bind a second media key (chrome only)
> 
>     3. You can use another tool like AutoHotkey to convert a Pause/Break keypress into Alt+N (Chrome or Firefox)
> 
> 
> Here is the documentation which explains why this isn't possible to do:
> [Chrome](https://developer.chrome.com/extensions/commands)
> [Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/commands)

Hey man! I forgot that AHK even existed. Got it working setup as Pause::!n woop woop
