### ISSUE TITLE
[BUT] Can't logout or detect new stations

### ISSUE THREAD

**Issue by angelhdzmultimedia** [pvrs12/Anesidora#40]
Recently I noticed I can't **log out**, and when I added a new station, it doesn't appear, even when I click on **Refresh Stations** in the settings. And yes, I click **Save**. I will remove the extension in Chrome and add it again to see if this fixes it. Thanks.

**Comment by angelhdzmultimedia** [comment]
### Update

The issue with adding new stations isn't an issue at all. It looks like when I added the station to my collection, it failed, so that's why it didn't appear in Anesidora. I tried again and it now appears.

The issue with Log Out is still an issue. I hit logout, save, then open Anesidora and I'm still logged in and not redirected to the Log In Screen.

**Comment by pvrs12** [comment]
I think this happens because the "logout" is actually just deleting the locally stored creds, but isn't invalidating your Pandora session. 

The quick workaround for this is to close/reopen your browser and it _should_ invalidate the Pandora session and ask you to login again. This isn't a priority for me to fix (as you could probably guess since I've left it for a year)...

I'll queue it up for the next time I make any API changes (which are very infrequent)

**Comment by angelhdzmultimedia** [comment]
> I think this happens because the "logout" is actually just deleting the locally stored creds, but isn't invalidating your Pandora session.
> 
> The quick workaround for this is to close/reopen your browser and it _should_ invalidate the Pandora session and ask you to login again. This isn't a priority for me to fix (as you could probably guess since I've left it for a year)...
> 
> I'll queue it up for the next time I make any API changes (which are very infrequent)

Thank you. I hope you are doing great. Be safe please!

**Comment by angelhdzmultimedia** [comment]
What happened to the UI? Did it change?

**Comment by pvrs12** [comment]
Yah, https://github.com/hucario helped make the UI look a lot cleaner.

If you'd prefer you can swap back to the old one in the options menu
