### ISSUE TITLE
options page doesn't seem to work with firefox on android

### ISSUE THREAD

**Issue by nswanson777777** [pvrs12/Anesidora#43]
Typing in anything into any of the fields doesn't seem to have any effect on the settings. Also the default hotkeys for play/pause and next do not seem to work either.

**Comment by pvrs12** [comment]
Firefox for Android isn't something I've tested heavily in development. It's a _huge_ pain to test on Android firefox due to the difficulty of creating a package for Android. 

The download stats only show 46 android users, so I'm not going to go out of my way to dev any fixes for it (especially hotkeys since they're not officially supported yet https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/commands)
