### ISSUE TITLE
Icons not rendering

### ISSUE THREAD

**Issue by pvrs12** [pvrs12/Anesidora#71]
For some reason the icons don't always render. It may be beneficial to add a fallback graphic or alt text.

**Comment by pvrs12** [comment]
May need help from @hucario on this one

**Comment by hucario** [comment]
This is on me- the UI needs a rework anyways. Again. Icons will change, but it'll be a lot simpler (using fonts for icons instead of the svg drop-shadow hack)

**Comment by cpgeek** [comment]
Thank you guys for all of the latest fixes and updates.  I really appreciate the work that you folks put in.  Is there a recommended method of showing appreciation / support for @pvrs12 and @hucario ?

**Comment by hucario** [comment]
> Thank you guys for all of the latest fixes and updates. I really appreciate the work that you folks put in. Is there a recommended method of showing appreciation / support for @pvrs12 and @hucario ?

going to [copy pvrs here for a moment](https://github.com/pvrs12/Anesidora/issues/67#issuecomment-841575545) and say:
I appreciate the offer, but I don't want to take money for this.
If you still want to donate, I personally suggest getting Pandora One ~~because I feel a little bad about removing ads~~ but it doesn't matter too much.
